homeassistant:
  name: Home
  latitude: !secret MY_LATITUDE
  longitude: !secret MY_LONGITUDE
  elevation: 315
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml

frontend:
  themes:
    blue:
      primary-color: "#356AA0"

http:
  api_password: !secret MY_API_PASS
  #ssl_certificate: !secret SSL_CERT
  #ssl_key: !secret SSL_KEY
  #base_url: !secret BASEURL
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
  use_x_forwarded_for: True
  trusted_networks:
    - 127.0.0.1
    - 192.168.7.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 5

config:

conversation:

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.7.1/24
    track_new_devices: yes
  - platform: icloud
    username: !secret ICLOUD_USER
    password: !secret ICLOUD_PASS
    track_new_devices: yes
  - platform: geofency
  - platform: owntracks
    track_new_devices: yes
  #- platform: bluetooth_tracker

discovery:

updater:
  #include_used_components: true

sun:

ios:

logbook:

history:

media_player:
  - platform: cast
    host: 192.168.7.48
  - platform: apple_tv
    host: 192.168.7.23
    login_id: !secret apple_tv_login
  - platform: roku
    host: 192.168.7.49
  - platform: vlc
    name: hass_speaker
    arguments: '--alsa-audio-device=hw:0,0'

tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

notify:
  - platform: ios
  - name: all_ios
    platform: group
    services:
      - service: ios_jeffreystonesiphone
      - service: ios_jeffreystonesipad
      - service: ios_katherinestonesiphone
  - name: jeff_ios
    platform: group
    services:
      - service: ios_jeffreystonesiphone
      - service: ios_jeffreystonesipad
 
mqtt:
 broker: 192.168.7.24
 port: 1883
 username: !secret MQTT_USER
 password: !secret MQTT_PASS


### Includes ###
alert: !include_dir_merge_named alerts/
group: !include groups.yaml
automation: !include_dir_merge_list automation
sensor: !include_dir_merge_list sensors
light: !include_dir_merge_list lights
switch: !include_dir_merge_list switches
script: !include_dir_merge_named scripts/
intent_script: !include intents/intents.yaml
scene: !include scenes.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
zone: !include zones.yaml

python_script:

### Devices and Services

ifttt:
  key: !secret IFTTT_API_KEY

cover:
  - platform: mqtt
    name: "Garage Door"
    state_topic: 'smartthings/Garage Door/contact'
    command_topic: 'smartthings/Garage Door/door'
    state_open: 'open'
    state_closed: 'closed'
    payload_open: 'open'
    payload_close: 'closed'
    retain: true
    optimistic: true

climate:
  platform: honeywell
  username: !secret HONEYWELL_USER
  password: !secret HONEYWELL_PASS
  name: First Floor
  region: us
  scan_interval: 600

alexa:


### Custom Commands

shell_command:
  alarm_off: pkill mpg123
  tornado_alarm: mpg123 /media/audio/Tornado_Siren.mp3
  door_chime: mpg123 /media/audio/Store_Door_Chime.mp3
  security_alarm: mpg123 /media/audio/security_siren.mp3
  
