### Views ###
default_view:
    name: Home
    view: yes
    icon: mdi:home
    entities:
      - group.house
      - group.security_system
      - group.security_status
      - group.garage_door
      - group.weather_alerts
      - group.temperature
      
lights:
  name: Lights
  view: yes
  icon: mdi:lightbulb
  entities:
    - group.living_room
    - group.loft
    - group.driveway
    - group.front_porch
    - group.kitchen
    - group.scenes

people:
  name: People
  view: yes
  icon: mdi:human-male-female
  entities:
    - group.jeffrey
    - group.katherine

media:
  name: media
  view: yes
  icon: mdi:theater
  entities:
    - group.tvs
    - group.gaming
    - media_player.apple_tv
    - media_player.living_room_tv
    - media_player.roku_5s6719003683
    - media_player.guest_tv

cars:
  name: Cars
  view: yes
  icon: mdi:car
  entities:
    - group.travel_times

homeassistant:
  name: HA 
  view: yes
  icon: mdi:home-automation
  entities:
    - group.ha_system_monitor
    - group.ha_version_info
    - group.file_size
    - group.internet
    - group.computers
    - group.home_automation

chores:
  name: Chores
  view: yes
  icon: mdi:calendar
  entities:
    - group.trash_schedule

security:
  name: Security
  view: yes
  icon: mdi:security
  entities:
    - group.modes
    - group.security_system
    - group.security_status
    - group.fire
    - group.doors
    - group.attic
    - group.garage

settings:
  name: Settings
  view: yes
  icon: mdi:settings
  entities:
    - group.automations
    - group.notifications

#################################################################################
### Grops ###
Security Status:
  control: hidden
  entities:
  - sensor.pws_alerts
  - sensor.garage_door
  - group.doors
  - sensor.smoke_kitchen
  - sensor.attic_door
  - input_boolean.garage_issue
  - input_boolean.security_alarm
  - input_boolean.tornado_alarm

Security System:
  control: hidden
  entities:
  - sensor.security_status
  - input_boolean.secure_mode

House:
  control: hidden
  entities:
  - sensor.family_presence
  - input_boolean.audible_notifications
  - input_boolean.vacation_mode
  - input_boolean.guest_mode

Doors:
  - binary_sensor.back_door
  - binary_sensor.front_door
  - binary_sensor.laundry_room_door

Attic:
  - binary_sensor.attic_door

Family:
  - device_tracker.jeffreystonesiphone
  - device_tracker.owntracks_jeffreystonesiphone
  - device_tracker.katherinestonesiphone

Jeffrey:
  - device_tracker.owntracks_jeffreystonesiphone
  - sensor.jeff_iphone_batt
  - sensor.jeff_destination
  - sensor.jeff_ett_home
  - input_boolean.jeff_heading_home
  - input_boolean.text_notify_jeff
  
Katherine:
  - device_tracker.katherinestonesiphone
  - sensor.kat_iphone_batt
  - sensor.kat_ett_home
  - input_boolean.kat_heading_home
  - input_boolean.text_notify_kat

Travel Times:
  - sensor.home_to_summit
  - sensor.home_to_zoo
  - sensor.jeff_ett_home
  - sensor.kat_ett_home

Living Room:
  - switch.fireplace_lights
  - light.tower_lamp
  - switch.strip_cord_1

Loft:
  - switch.loft_lamp

Kitchen:
  - switch.kitchen_cabinets
  - switch.kitchen_light_strip

Scenes:
  - scene.livingroom_dim
  - scene.livingroom_night
  - scene.livingroom_normal
  - scene.movie_time

Outside Lights:
  - switch.driveway_light
  - switch.side_door
  - group.front_porch

Driveway:
  - switch.driveway_light
  - switch.side_door
  
Front Porch:
  - switch.front_porch_left
  - switch.front_porch_right

Thermostat:
  - climate.first_floor

Sun and Moon:
  - sun.sun
  - sun.next_rising
  - sun.next_setting
  - sensor.moon

Weather Summary:
  - climate.first_floor
  - sensor.dark_sky_summary
  - sensor.dark_sky_apparent_temperature
  - sensor.dark_sky_humidity
  - sensor.dark_sky_minutely_summary

Weather Forecast:
  - sensor.dark_sky_minutely_summary
  - sensor.dark_sky_hourly_summary
  - sensor.dark_sky_daily_summary

Temperature:
  - climate.first_floor
  - sensor.dark_sky_apparent_temperature
  - sensor.dark_sky_humidity
  - sensor.dark_sky_dew_point
  - sensor.accurite_back_porch_temperature
  - sensor.accurite_back_porch_humidity
  - sensor.accurite_garage_temperature
  - sensor.accurite_garage_humidity

Precipitation:
  - sensor.dark_sky_nearest_storm_distance
  - sensor.dark_sky_precip
  - sensor.dark_sky_precip_probability
  - sensor.pws_precip_today_in
  - sensor.dark_sky_visibility
  - sensor.dark_sky_pressure

Wind:
  - sensor.pws_wind_mph
  - sensor.pws_wind_gust_mph
  - sensor.pws_wind_dir

Daily Stats:
  - sensor.dark_sky_daily_low_temperature
  - sensor.dark_sky_daily_high_temperature
  - sensor.dark_sky_daily_max_precip_intensity

Internet:
  - sensor.speedtest_ping
  - sensor.speedtest_download
  - sensor.speedtest_upload

Hvac:
  - sensor.hvac_first_temp
  - sensor.hvac_first_current_temp
  - sesnor.hvac_first_mode

Home Automation:
  - sensor.smartthings
  - sensor.amazon_dot_lr
  - sensor.amazon_dot_kn
  - sensor.honeywell
  - sensor.eero_loft
  - sensor.eero_livingroom

#Cameras:
#  - device_tracker.ipcam_00626e46eb09_1
TVs:
  - sensor.samsungtv
  - sensor.xboxone

Computers:
  - sensor.jeff_ipad
  - sensor.jeff_mbp
  - sensor.jeff_work_mbp
  - sensor.kat_ipad
  - sensor.kat_mini

Garage Door:
  - cover.garage_door

Modes:
  control: hidden
  entities:
    - input_boolean.secure_mode
    - input_boolean.vacation_mode
    - input_boolean.guest_mode
  
Automation:
  - input_boolean.automations

Zones:
  - binary_sensor.zone_3

Garage:
  - sensor.garage_door
  - binary_sensor.garage_motion

Fire:
  - sensor.smoke_kitchen

HA System Monitor:
  - sensor.cpu
  - sensor.disk_use_percent_
  - sensor.memory_use_percent
  - sensor.network_in_eth0
  - sensor.network_out_eth0
  - sensor.last_boot
  - sensor.ha_uptime
  - sensor.lets_encrypt_expiration

HA Version Info:
  - sensor.installed_version
  - sensor.current_ha_version

File Size:
  control: hidden
  entities:
    - sensor.ha_v2db
    - sensor.ha_log

#Zwave:
#  - zwave.aeotec_zw090_zstick_gen5_us

Weather Alerts:
  control: hidden
  entities:
  - sensor.pws_alerts
  - sensor.allergy_index_average_forecasted
  - sensor.allergy_index_average_historical
  - sensor.allergy_index_today
  - sensor.allergy_index_tomorrow
  - sensor.cold__flu_forecasted_average

Trash Schedule:
  - input_select.trash_pickup
  - input_select.recycle_pickup
  - input_boolean.trash_notification
