- platform: google_travel_time
  name: "Jeff ETT Home"
  api_key: !secret google_api
  origin: device_tracker.owntracks_jeffreystonesiphone
  destination: zone.home
- platform: google_travel_time
  name: "Kat ETT Home"
  api_key: !secret google_api
  origin: device_tracker.katherinestonesiphone
  destination: zone.home
- platform: google_travel_time
  name: "Home To Summit"
  api_key: !secret google_api
  origin: zone.home
  destination: zone.summit
- platform: google_travel_time
  name: "Home To Zoo"
  api_key: !secret google_api
  origin: zone.home
  destination: zone.zoo_atlanta
