- platform: mqtt
  name: "Lockdown Status"
  state_topic: "house/lockdown/status"
- platform: template
  sensors:
    zone_status:
      friendly_name: Zones
      unit_of_measurement: ''
      value_template: >-
          {%- if is_state("sensor.zone_3", "open") %}
            Open
          {%- elif is_state("sensor.zone_3", "closed") %}
            Closed
          {% else %}
            N/A
          {%- endif %}
      icon_template: >-
        {%- if is_state("sensor.zone_status", "Open") %}
          mdi:lock-open
        {%- elif is_state("sensor.zone_status", "Closed") %}
          mdi:lock-plus
        {% else %}
          mdi:sync-alert
        {%- endif %}


