- platform: template
  sensors:
    garage_door:
      friendly_name: Garage Door
      unit_of_measurement: ''
      value_template: >-
          {%- if is_state("cover.garage_door", "open") %}
                Open
            {% elif is_state("cover.garage_door", "closed") %}
                Closed
            {% else %}
                Unknown
            {%- endif %}
      icon_template: >-
        {%- if is_state("cover.garage_door", "closed") %}
          mdi:garage
        {%- elif is_state("cover.garage_door", "open") %}
          mdi:garage-open
        {% else %}
          mdi:sync-alert
        {%- endif %}
- platform: mqtt
  name: "Back Door"
  state_topic: "smartthings/Back Door/contact"
  payload_on: "open"
  payload_off: "closed"
  retain: true
- platform: mqtt
  name: "Kitchen Smoke"
  state_topic: "smartthings/Kitchen Smoke/smoke"
  payload_on: "smoke"
  payload_off: "clear"
  retain: true
- platform: mqtt
  name: "Garage Door Contact"
  state_topic: "smartthings/Garage Door/contact"
  payload_on: "open"
  payload_off: "closed"
  retain: true
- platform: mqtt
  name: "Front Door"
  state_topic: "smartthings/Front Door/contact"
  payload_on: "open"
  payload_off: "closed"
  retain: true
- platform: mqtt
  name: "Laundry Room Door"
  state_topic: "smartthings/Laundry Room Door/contact"
  payload_on: "open"
  payload_off: "closed"
  retain: true
- platform: mqtt
  name: "Kat Presence"
  state_topic: "smartthings/Kat/presence"
  payload_on: "present"
  payload_off: "not present"
  retain: true
- platform: mqtt
  name: "Jeff Presence"
  state_topic: "smartthings/Jeffrey/presence"
  payload_on: "present"
  payload_off: "not present"
  retain: true