
#
#
# DoorAutomations
#
#
#####################
- alias: Door Opened
  trigger:
  - platform: state
    entity_id: group.doors
    from: closed
    to: open
  condition:
  - condition: state
    entity_id: input_boolean.audible_notifications
    state: 'on'
  action:
  - service: shell_command.door_chime

- alias: Door Closed
  trigger:
  - platform: state
    entity_id: group.doors
    from: open
    to: closed
  condition:
  - condition: state
    entity_id: input_boolean.audible_notifications
    state: 'on'
  action:
  - service: shell_command.door_chime


# - alias: Back Door Opened
#   trigger:
#   - platform: state
#     entity_id: sensor.back_door
#     from: closed
#     to: open
#   condition:
#   - condition: state
#     entity_id: input_boolean.audible_notifications
#     state: 'on'
#   action:
#   - service: shell_command.door_chime

# - alias: Back Door Closed
#   trigger:
#   - platform: state
#     entity_id: sensor.zone_3
#     from: open
#     to: closed
#   condition:
#   - condition: state
#     entity_id: input_boolean.audible_notifications
#     state: 'on'
#   action:
#   - service: shell_command.door_chime

# - alias: Front Door Opened
#   trigger:
#   - platform: state
#     entity_id: sensor.front_door
#     from: closed
#     to: open
#   condition:
#   - condition: state
#     entity_id: input_boolean.audible_notifications
#     state: 'on'
#   action:
#   - service: shell_command.door_chime

# - alias: Front Door Closed
#   trigger:
#   - platform: state
#     entity_id: sensor.front_3
#     from: open
#     to: closed
#   condition:
#   - condition: state
#     entity_id: input_boolean.audible_notifications
#     state: 'on'
#   action:
#   - service: shell_command.door_chime

# - alias: Laundry Room Door Opened
#   trigger:
#   - platform: state
#     entity_id: sensor.laundry_room_door
#     from: closed
#     to: open
#   condition:
#   - condition: state
#     entity_id: input_boolean.audible_notifications
#     state: 'on'
#   action:
#   - service: shell_command.door_chime

# - alias: Laundry Roomm Door Closed
#   trigger:
#   - platform: state
#     entity_id: sensor.laundry_room_door
#     from: open
#     to: closed
#   condition:
#   - condition: state
#     entity_id: input_boolean.audible_notifications
#     state: 'on'
#   action:
#   - service: shell_command.door_chime