#
#
# Weather
#
############

- alias: Cloudy, inside on if home
  trigger:
  - platform: time
    at: '16:00:00'
  condition:
  - condition: numeric_state
    entity_id: sensor.dark_sky_cloud_coverage
    above: 70
  - condition: state
    entity_id: group.family
    state: home
  action:
  - service: notify.ios_jeffreystonesiphone
    data:
      message: Cloudy, turning on LR Lamp

- alias: Kill Audible Tornado Alarm
  trigger:
  - platform: state
    entity_id: input_boolean.tornado_alarm
    to: 'off'
  action:
    - service: script.kill_audible_alarm
    - service: homeassistant.turn_off
      entity_id: script.tornado_alarm


- alias: Sound Audible Tornado Alarm
  trigger:
  - platform: state
    entity_id: input_boolean.tornado_alarm
    to: "on"
  action:
    - service: script.tornado_warning
    - service: homeassistant.turn_on
      entity_id: script.tornado_alarm

- alias: Wx Alert Notification
  - trigger:
    platform: state
    entity_id: sensor.pws_alerts
  action:
  - service: script.wxalert_tile

- alias: Weather Warning Tornado
  trigger:
    - platform: numeric_state
      entity_id: sensor.pws_alerts
      above: 1
  condition:
     condition: or
     conditions:
       - condition: template
         value_template: '{{ states.sensor.pws_alerts.attributes.Description == "Tornado Warning" }}'
       - condition: template
         value_template: '{{ states.sensor.pws_alerts.attributes.Description_TOR == "Tornado Warning" }}'
  action:
    - service: homeassistant.turn_on
        entity_id: input_boolean.tornado_alarm



